[profile.default]
src = 'src'
test = 'test'
script = 'scripts'
out = 'out'
libs = ['lib', '../node_modules']
solc_version = '0.8.24'
optimizer = true
optimizer_runs = 200
via_ir = true
fs_permissions = [
    { access = "read", path = "../node_modules" }
]

[rpc_endpoints]
arc-testnet = "${ARC_TESTNET_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"
# Add more networks as needed
# mainnet = "${MAINNET_RPC_URL}"
